/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.main;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.Color;
import javax.swing.UIManager;

/**
 *
 * @author desan
 */
public class FIllPdfDialog extends javax.swing.JDialog {

    /**
     * Creates new form FIllPdfDialog
     */
    public FIllPdfDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Establecer el Look and Feel de FlatLaf
    
        FlatLightLaf.setup();
        this.getContentPane().setBackground(Color.decode("#50bbdf"));
        jLabelTitle.putClientProperty("FlatLaf.styleClass", "h1");
        
        //set style to Jlabel
        jLabelCorreo.putClientProperty("FlatLaf.styleClass", "h4");
        jLabelNombreEmp.putClientProperty("FlatLaf.styleClass", "h4");
        jLabelNumeroEmp.putClientProperty("FlatLaf.styleClass", "h4");
        jLabelDepartamento.putClientProperty("FlatLaf.styleClass", "h4");
        jLabelDescEquipo.putClientProperty("FlatLaf.styleClass", "h4");
        jLabelModeloEquipo.putClientProperty("FlatLaf.styleClass", "h4");
        jLabelEtiquetaEquipo.putClientProperty("FlatLaf.styleClass", "h4");
        
        
         //set style to JTextFields
        jTextFieldCorreo.putClientProperty("FlatLaf.styleClass", "large");
        jTextFieldNombreEmp.putClientProperty("FlatLaf.styleClass", "large");
        jTextFieldNumeroEmp.putClientProperty("FlatLaf.styleClass", "large");
        jTextFieldDepartamento.putClientProperty("FlatLaf.styleClass", "large");
        jTextFieldDescEquipo.putClientProperty("FlatLaf.styleClass", "large");
        jTextFieldModeloEquipo.putClientProperty("FlatLaf.styleClass", "large");
        jTextFieldEtiquetaEquipo.putClientProperty("FlatLaf.styleClass", "large");
        
        
        
        
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelNombreEmp = new javax.swing.JLabel();
        jLabelNumeroEmp = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelDescEquipo = new javax.swing.JLabel();
        jLabelModeloEquipo = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldModeloEquipo = new javax.swing.JTextField();
        jTextFieldNombreEmp = new javax.swing.JTextField();
        jTextFieldNumeroEmp = new javax.swing.JTextField();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jTextFieldDescEquipo = new javax.swing.JTextField();
        jLabelEtiquetaEquipo = new javax.swing.JLabel();
        jTextFieldEtiquetaEquipo = new javax.swing.JTextField();
        jButtonFirmar = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabelCorreo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCorreo.setText("Correo");

        jLabelNombreEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNombreEmp.setText("Nombre del empleado");

        jLabelNumeroEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroEmp.setText("Numero del empleado");

        jLabelDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDepartamento.setText("Departamento");

        jLabelDescEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDescEquipo.setText("Descripcion del equipo");

        jLabelModeloEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelModeloEquipo.setText("Modelo del equipo");

        jTextFieldCorreo.setBackground(Color.decode("#ede6db")
        );
        jTextFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCorreo.setText("Correo@example.com");
        jTextFieldCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldCorreoMouseClicked(evt);
            }
        });

        jTextFieldModeloEquipo.setBackground(Color.decode("#ede6db")
        );
        jTextFieldModeloEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldModeloEquipo.setText("Descripcion del equipo");
        jTextFieldModeloEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldModeloEquipoMouseClicked(evt);
            }
        });
        jTextFieldModeloEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloEquipoActionPerformed(evt);
            }
        });

        jTextFieldNombreEmp.setBackground(Color.decode("#ede6db")
        );
        jTextFieldNombreEmp.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombreEmp.setText("Juan Pérez Ejemplo");
        jTextFieldNombreEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreEmpMouseClicked(evt);
            }
        });

        jTextFieldNumeroEmp.setBackground(Color.decode("#ede6db")
        );
        jTextFieldNumeroEmp.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNumeroEmp.setText("Juan Pérez Ejemplo");
        jTextFieldNumeroEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNumeroEmpMouseClicked(evt);
            }
        });

        jTextFieldDepartamento.setBackground(Color.decode("#ede6db")
        );
        jTextFieldDepartamento.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDepartamento.setText("Departamento");
        jTextFieldDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDepartamentoMouseClicked(evt);
            }
        });

        jTextFieldDescEquipo.setBackground(Color.decode("#ede6db")
        );
        jTextFieldDescEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDescEquipo.setText("Descripcion del equipo");
        jTextFieldDescEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldDescEquipoMouseClicked(evt);
            }
        });
        jTextFieldDescEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescEquipoActionPerformed(evt);
            }
        });

        jLabelEtiquetaEquipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEtiquetaEquipo.setText("Etiqueta del equipo");

        jTextFieldEtiquetaEquipo.setBackground(Color.decode("#ede6db")
        );
        jTextFieldEtiquetaEquipo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldEtiquetaEquipo.setText("Etiqueta  del equipo");
        jTextFieldEtiquetaEquipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEtiquetaEquipoMouseClicked(evt);
            }
        });
        jTextFieldEtiquetaEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEtiquetaEquipoActionPerformed(evt);
            }
        });

        jButtonFirmar.setBackground(Color.decode("#e85645")
        );
        jButtonFirmar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFirmar.setText("Firmar PDF");
        jButtonFirmar.setBorder(null);
        jButtonFirmar.setBorderPainted(false);
        jButtonFirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldCorreo)
            .addComponent(jLabelNombreEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelNumeroEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldNombreEmp, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabelDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelDescEquipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextFieldDescEquipo)
            .addComponent(jLabelModeloEquipo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTextFieldEtiquetaEquipo)
            .addComponent(jTextFieldModeloEquipo, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jTextFieldNumeroEmp, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEtiquetaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jButtonFirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombreEmp)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNumeroEmp)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldNumeroEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDepartamento)
                .addGap(24, 24, 24)
                .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDescEquipo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDescEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelModeloEquipo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldModeloEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEtiquetaEquipo)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldEtiquetaEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonFirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Captura los datos de la carta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldCorreoMouseClicked
        // TODO add your handling code here:
        jTextFieldCorreo.setText("");
    }//GEN-LAST:event_jTextFieldCorreoMouseClicked

    private void jTextFieldModeloEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldModeloEquipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloEquipoMouseClicked

    private void jTextFieldNombreEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreEmpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreEmpMouseClicked

    private void jTextFieldNumeroEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNumeroEmpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroEmpMouseClicked

    private void jTextFieldDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDepartamentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDepartamentoMouseClicked

    private void jTextFieldModeloEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloEquipoActionPerformed

    private void jTextFieldDescEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldDescEquipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescEquipoMouseClicked

    private void jTextFieldDescEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescEquipoActionPerformed

    private void jTextFieldEtiquetaEquipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEtiquetaEquipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtiquetaEquipoMouseClicked

    private void jTextFieldEtiquetaEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEtiquetaEquipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEtiquetaEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIllPdfDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIllPdfDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIllPdfDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIllPdfDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FIllPdfDialog dialog = new FIllPdfDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                try {
                        UIManager.setLookAndFeel( new FlatMaterialLighterIJTheme() );
                        
                    } catch( Exception ex ) {
                        System.err.println( "Failed to initialize LaF" );
                    }
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFirmar;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDescEquipo;
    private javax.swing.JLabel jLabelEtiquetaEquipo;
    private javax.swing.JLabel jLabelModeloEquipo;
    private javax.swing.JLabel jLabelNombreEmp;
    private javax.swing.JLabel jLabelNumeroEmp;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldDescEquipo;
    private javax.swing.JTextField jTextFieldEtiquetaEquipo;
    private javax.swing.JTextField jTextFieldModeloEquipo;
    private javax.swing.JTextField jTextFieldNombreEmp;
    private javax.swing.JTextField jTextFieldNumeroEmp;
    // End of variables declaration//GEN-END:variables
}
