/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.main;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/**
 *
 * @author desan
 */
public class testHome extends javax.swing.JFrame {

    /**
     * Creates new form testHome
     */
    public testHome() {
        initComponents();
        LogoLabel.setIcon(loadAndScaleIcon("/com/src/Logo.png", 155, 175));
        
        jLabelCRUD.putClientProperty("FlatLaf.styleClass", "h2");
        
        TestTable tab1 = new TestTable();
                // Asegurarse de que JPanelTabs usa BorderLayout
         JPanelTabs.setLayout(new BorderLayout());

         // Eliminar todos los componentes actuales de JPanelTabs
         JPanelTabs.removeAll();
         
         tab1.setPreferredSize(JPanelTabs.getSize());

         // Añadir tab1 al centro de JPanelTabs
         JPanelTabs.add(tab1, BorderLayout.CENTER);

         // Actualizar el layout de JPanelTabs
         JPanelTabs.revalidate();
         JPanelTabs.repaint();
         
         
         //Pone logo al JFRAME
         URL iconURL = getClass().getResource("/com/src/iconDefault.png");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        
         
        
         
        
    }
    
    
    
    //Cargar y escalar ícono 
     private ImageIcon loadAndScaleIcon(String path, int width, int height) {
        ImageIcon originalIcon = new ImageIcon(getClass().getResource(path));
        if (originalIcon.getIconWidth() == -1) {
            System.err.println("Error: No se pudo cargar la imagen en " + path);
            return null;
        }
        Image scaledImage = originalIcon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        return new ImageIcon(scaledImage);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        JPanelTabs = new javax.swing.JPanel();
        PanelOpc = new javax.swing.JPanel();
        LogoLabel = new javax.swing.JLabel();
        JButtonHome = new javax.swing.JButton();
        JButtonReportes = new javax.swing.JButton();
        JButtonEmpleados = new javax.swing.JButton();
        JButtonCrearCarta = new javax.swing.JButton();
        JButtonCrearCarta1 = new javax.swing.JButton();
        jLabelCRUD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1350, 636));

        background.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout JPanelTabsLayout = new javax.swing.GroupLayout(JPanelTabs);
        JPanelTabs.setLayout(JPanelTabsLayout);
        JPanelTabsLayout.setHorizontalGroup(
            JPanelTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
        );
        JPanelTabsLayout.setVerticalGroup(
            JPanelTabsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelOpc.setBackground(Color.decode("#50bbdf"));

        LogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/Logo.png"))); // NOI18N

        JButtonHome.setBackground(Color.decode("#50bbdf"));
        JButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonHome.setForeground(new java.awt.Color(0, 0, 0));
        JButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/home_png_16px.png"))); // NOI18N
        JButtonHome.setText("Home");
        JButtonHome.setBorder(null);
        JButtonHome.setBorderPainted(false);

        JButtonReportes.setBackground(Color.decode("#50bbdf"));
        JButtonReportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonReportes.setForeground(new java.awt.Color(0, 0, 0));
        JButtonReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/adddoc_png_16px.png"))); // NOI18N
        JButtonReportes.setText("Reportes");
        JButtonReportes.setBorder(null);
        JButtonReportes.setBorderPainted(false);

        JButtonEmpleados.setBackground(Color.decode("#50bbdf"));
        JButtonEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        JButtonEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/user_png_16px.png"))); // NOI18N
        JButtonEmpleados.setText("Empleados");
        JButtonEmpleados.setBorder(null);
        JButtonEmpleados.setBorderPainted(false);
        JButtonEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEmpleadosActionPerformed(evt);
            }
        });

        JButtonCrearCarta.setBackground(Color.decode("#50bbdf"));
        JButtonCrearCarta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonCrearCarta.setForeground(new java.awt.Color(0, 0, 0));
        JButtonCrearCarta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/adddoc_png_16px.png"))); // NOI18N
        JButtonCrearCarta.setText("Crear Carta");
        JButtonCrearCarta.setBorder(null);
        JButtonCrearCarta.setBorderPainted(false);
        JButtonCrearCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCrearCartaActionPerformed(evt);
            }
        });

        JButtonCrearCarta1.setBackground(Color.decode("#50bbdf"));
        JButtonCrearCarta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JButtonCrearCarta1.setForeground(new java.awt.Color(0, 0, 0));
        JButtonCrearCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/exit_png_16px.png"))); // NOI18N
        JButtonCrearCarta1.setText("Cerrar Sesión");
        JButtonCrearCarta1.setBorder(null);
        JButtonCrearCarta1.setBorderPainted(false);
        JButtonCrearCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCrearCarta1ActionPerformed(evt);
            }
        });

        jLabelCRUD.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCRUD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCRUD.setText("CRUD FRAGUA");

        javax.swing.GroupLayout PanelOpcLayout = new javax.swing.GroupLayout(PanelOpc);
        PanelOpc.setLayout(PanelOpcLayout);
        PanelOpcLayout.setHorizontalGroup(
            PanelOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
            .addComponent(JButtonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JButtonEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JButtonCrearCarta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JButtonCrearCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JButtonHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelOpcLayout.setVerticalGroup(
            PanelOpcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOpcLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelCRUD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButtonCrearCarta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(JButtonCrearCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(PanelOpc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOpc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(JPanelTabs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonCrearCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCrearCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonCrearCartaActionPerformed

    private void JButtonEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonEmpleadosActionPerformed

    private void JButtonCrearCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCrearCarta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonCrearCarta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
               try {
                        UIManager.setLookAndFeel( new FlatMaterialLighterIJTheme() );
                    } catch( Exception ex ) {
                        System.err.println( "Failed to initialize LaF" );
                    }
                
                new testHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonCrearCarta;
    private javax.swing.JButton JButtonCrearCarta1;
    private javax.swing.JButton JButtonEmpleados;
    private javax.swing.JButton JButtonHome;
    private javax.swing.JButton JButtonReportes;
    private javax.swing.JPanel JPanelTabs;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel PanelOpc;
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabelCRUD;
    // End of variables declaration//GEN-END:variables
}
