/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.main;

import ClassesOfDtos.Tab1Data;
import FunctionalityClasses.ApiClient;
import com.component.table.PanelSDD;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author desan
 */
public class TestTable extends javax.swing.JPanel {

    /**
     * Creates new form testTable
     */
    public TestTable() {
        initComponents();

        ApiClient apiClient = new ApiClient();
        String url = "http://localhost:8080/api/v1/empleados/home"; // Reemplaza con tu URL
        List<Tab1Data> empleados = apiClient.makeGetRequestForTab1(url);

        // Crear JTable y DefaultTableModel
        String[] columnNames = {"Numero Empleado", "Nombre Emp", "ID Carta", "Revision", "Fecha Entrega"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        

        // Llenar el modelo con datos
        if (empleados != null) {
            for (Tab1Data emp : empleados) {
                Object[] row = {
                        emp.getNumeroEmpleado(),
                        emp.getNombreEmp(),
                        emp.getIdCarta(),
                        emp.getRevision(),
                        emp.getFechaEntrega()
                };
                model.addRow(row);
            }
        }

        tableHome.setModel(model);

        PanelSDD panelSDD = new PanelSDD();
        jPanelButtons.add(panelSDD, BorderLayout.CENTER);
        jPanelButtons.setBackground(Color.WHITE);
        jPanelButtons.revalidate();
        jPanelButtons.repaint();

        //Establece el formato de texto
        Title.putClientProperty("FlatLaf.styleClass", "h1");

        //Establece el tema
        try {
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableHome = new javax.swing.JTable();
        jPanelButtons = new javax.swing.JPanel();

        Title.setForeground(new java.awt.Color(0, 0, 0));
        Title.setText("Lista de PDF´S");

        tableHome.setForeground(new java.awt.Color(0, 0, 0));
        tableHome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Empleado", "Nombre", "ID_Carta", "Revisión", "Fecha Expedición"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableHome.setCellEditor(null);
        tableHome.setRowHeight(40);
        tableHome.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableHome.setShowHorizontalLines(true);
        tableHome.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tableHome);

        jPanelButtons.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title)
                    .addComponent(jPanelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableHome;
    // End of variables declaration//GEN-END:variables
}
