/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

/**
 *
 * @author Gol D. Sergio
 */
public class UIMain extends javax.swing.JFrame {

    /**
     * Creates new form uiMain
     */
    public UIMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        homeButton = new com.view.custombutton.CustomButton();
        pdfButton = new com.view.custombutton.CustomButton();
        employeButton = new com.view.custombutton.CustomButton();
        newPdfButton = new com.view.custombutton.CustomButton();
        jLabel2 = new javax.swing.JLabel();
        profileButton = new com.view.custombutton.CustomButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        customButton1 = new com.view.custombutton.CustomButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);

        background.setBackground(new java.awt.Color(253, 253, 253));
        background.setMaximumSize(new java.awt.Dimension(1920, 1080));
        background.setMinimumSize(new java.awt.Dimension(960, 540));
        background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        background.setRequestFocusEnabled(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(80, 187, 223));
        kGradientPanel1.setkStartColor(new java.awt.Color(80, 187, 223));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(200, 760));

        homeButton.setForeground(new java.awt.Color(51, 51, 51));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/home_png_16px.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorderColor(new java.awt.Color(80, 187, 223));
        homeButton.setColor(new java.awt.Color(80, 187, 223));
        homeButton.setColorClick(new java.awt.Color(0, 156, 210));
        homeButton.setColorOver(new java.awt.Color(228, 91, 105));
        homeButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        homeButton.setIconTextGap(25);
        homeButton.setMargin(new java.awt.Insets(2, 18, 3, 14));
        homeButton.setRadius(10);
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        pdfButton.setForeground(new java.awt.Color(51, 51, 51));
        pdfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/docs_png_16px.png"))); // NOI18N
        pdfButton.setText("Reportes");
        pdfButton.setBorderColor(new java.awt.Color(80, 187, 223));
        pdfButton.setColor(new java.awt.Color(80, 187, 223));
        pdfButton.setColorClick(new java.awt.Color(0, 156, 210));
        pdfButton.setColorOver(new java.awt.Color(228, 91, 105));
        pdfButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        pdfButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pdfButton.setIconTextGap(20);
        pdfButton.setMargin(new java.awt.Insets(2, 18, 3, 14));
        pdfButton.setRadius(10);
        pdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfButtonActionPerformed(evt);
            }
        });

        employeButton.setForeground(new java.awt.Color(51, 51, 51));
        employeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/users_png_16px.png"))); // NOI18N
        employeButton.setText("Empleados");
        employeButton.setBorderColor(new java.awt.Color(80, 187, 223));
        employeButton.setColor(new java.awt.Color(80, 187, 223));
        employeButton.setColorClick(new java.awt.Color(0, 156, 210));
        employeButton.setColorOver(new java.awt.Color(228, 91, 105));
        employeButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        employeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        employeButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        employeButton.setIconTextGap(15);
        employeButton.setInheritsPopupMenu(true);
        employeButton.setMargin(new java.awt.Insets(2, 18, 3, 14));
        employeButton.setRadius(10);

        newPdfButton.setForeground(new java.awt.Color(51, 51, 51));
        newPdfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/adddoc_png_16px.png"))); // NOI18N
        newPdfButton.setText("Crear Carta");
        newPdfButton.setBorderColor(new java.awt.Color(80, 187, 223));
        newPdfButton.setColor(new java.awt.Color(80, 187, 223));
        newPdfButton.setColorClick(new java.awt.Color(0, 156, 210));
        newPdfButton.setColorOver(new java.awt.Color(228, 91, 105));
        newPdfButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        newPdfButton.setIconTextGap(10);
        newPdfButton.setRadius(10);
        newPdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPdfButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/LogoFragua.png"))); // NOI18N

        profileButton.setForeground(new java.awt.Color(51, 51, 51));
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/user_png_16px.png"))); // NOI18N
        profileButton.setText("Perfil");
        profileButton.setBorderColor(new java.awt.Color(80, 187, 223));
        profileButton.setColor(new java.awt.Color(80, 187, 223));
        profileButton.setColorClick(new java.awt.Color(0, 156, 210));
        profileButton.setColorOver(new java.awt.Color(228, 91, 105));
        profileButton.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        profileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileButton.setIconTextGap(20);
        profileButton.setMargin(new java.awt.Insets(2, 18, 3, 14));
        profileButton.setRadius(10);
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText(" CRUD FRAGUA");

        jPanel1.setBackground(new java.awt.Color(228, 91, 105));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        customButton1.setBackground(new java.awt.Color(80, 187, 223));
        customButton1.setForeground(new java.awt.Color(51, 51, 51));
        customButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/src/exit_png_16px.png"))); // NOI18N
        customButton1.setText("Cerrar Sesión");
        customButton1.setColor(new java.awt.Color(80, 187, 223));
        customButton1.setColorClick(new java.awt.Color(0, 156, 210));
        customButton1.setColorOver(new java.awt.Color(228, 91, 105));
        customButton1.setFont(new java.awt.Font("OCR A Extended", 1, 10)); // NOI18N
        customButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        customButton1.setIconTextGap(15);
        customButton1.setRadius(10);
        customButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(newPdfButton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(employeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pdfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(customButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(pdfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(employeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(newPdfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(customButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        background.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(1720, 50));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1730, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        background.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 1730, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1920, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void newPdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPdfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newPdfButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonActionPerformed

    private void pdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pdfButtonActionPerformed

    private void customButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private com.view.custombutton.CustomButton customButton1;
    private com.view.custombutton.CustomButton employeButton;
    private com.view.custombutton.CustomButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private com.view.custombutton.CustomButton newPdfButton;
    private com.view.custombutton.CustomButton pdfButton;
    private com.view.custombutton.CustomButton profileButton;
    // End of variables declaration//GEN-END:variables
}
